apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/lucaastorres7/k8s-study
    targetRevision: HEAD
    path: argocd
    directory:
      recurse: true
  destination:
    name: "kind-in-cluster"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true